dist: trusty
language: cpp
matrix:
  fast_finish: true
  include:
  - compiler: clang
    env: OS=linux COMPILER=clang-4.0 DOCKER_TAG=ubuntu-17.04 BUILD_TYPE=release
    os: linux
    script:
    - build-tools/ci/travis/build.sh "teem" "docker-${DOCKER_TAG}"
      --source-directory=${TRAVIS_BUILD_DIR}
      --build-directory=${TRAVIS_BUILD_DIR}/build
      --target-system=${OS}
      --compiler=${COMPILER}
      --target-architecture=x86_64
      --build-type=${BUILD_TYPE}
      --link-type=shared
      --build
      --test
      --install
      --install-directory=${TRAVIS_BUILD_DIR}/install
      --analyze
      --add-analyzer=cppcheck
      --analyze-output-directory=${TRAVIS_BUILD_DIR}/metrics_${OS}/
      --coverage
      --coverage-output-directory=${TRAVIS_BUILD_DIR}/metrics_${OS}/coverage
  - compiler: gcc
    env: OS=linux COMPILER=gcc-6 DOCKER_TAG=ubuntu-17.04 BUILD_TYPE=release
    os: linux
    script:
    - build-tools/ci/travis/build.sh "teem" "docker-${DOCKER_TAG}"
      --source-directory=${TRAVIS_BUILD_DIR}
      --build-directory=${TRAVIS_BUILD_DIR}/build
      --target-system=${OS}
      --compiler=${COMPILER}
      --target-architecture=x86_64
      --build-type=${BUILD_TYPE}
      --link-type=shared
      --build
      --test
      --install
      --install-directory=${TRAVIS_BUILD_DIR}/install
  - compiler: clang
    env: OS=linux COMPILER=clang-4.0 DOCKER_TAG=ubuntu-17.04 BUILD_TYPE=release
    os: linux
    script:
    - build-tools/ci/travis/build.sh "teem" "docker-${DOCKER_TAG}"
      --source-directory=${TRAVIS_BUILD_DIR}
      --build-directory=${TRAVIS_BUILD_DIR}/build
      --target-system=${OS}
      --compiler=${COMPILER}
      --target-architecture=x86_64
      --build-type=${BUILD_TYPE}
      --link-type=shared
      --build
      --test
      --install
      --install-directory=${TRAVIS_BUILD_DIR}/install
  - compiler: clang
    env: COMPILER=clang-3.9 OS=macos BUILD_TYPE=release
    os: osx
    osx_image: xcode8.2
    install:
    - build-tools/ci/travis/install_osx.sh
    script:
    - build-tools/ci/travis/build.sh "teem" "native"
      --source-directory=${TRAVIS_BUILD_DIR}
      --build-directory=${TRAVIS_BUILD_DIR}/build
      --target-system=${OS}
      --compiler=${COMPILER}
      --target-architecture=x86_64
      --build-type=${BUILD_TYPE}
      --link-type=shared
      --build
      --test
      --install
      --install-directory=${TRAVIS_BUILD_DIR}/install
services:
- docker
sudo: required